Workaround undefined symbol error
These errors were seen:
  libkoi.a(util_kernels.cu.o): undefined reference to symbol 'cublasGemmEx@@libcublas.so.12'
  libcublas.so.12: error adding symbols: DSO missing from command line

This looks like a bad configuration on torch's part, but we can work
around this by forcing the linker to pull in dependencies (which is
apparently the default behaviour, so I'm guessing newer versions of ld
have changed?)