[INSTX-4400] Remove CUDA_VERSION from our version header
This conflicts with the one in torch:

  dorado_version.h:5: error: "CUDA_VERSION" redefined
    #define CUDA_VERSION 102
  cuda.h:237: note: this is the location of the previous definition
    #define CUDA_VERSION 10020